# Generated by Django 5.1.6 on 2025-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemlog',
            name='date',
            field=models.DateField(),
        ),
    ]
