# Generated by Django 5.1.6 on 2025-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fooditemlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='proteins_per_100g',
            field=models.FloatField(default=0),
        ),
    ]
