# Generated by Django 5.1.6 on 2025-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'Малорухливий спосіб життя, відсутність фізичних навантажень'), (1.375, 'Легка активність (легкі тренування 1-3 рази на тиждень)'), (1.55, 'Помірна активність (помірні тренування 3-5 разів на тиждень)'), (1.725, 'Висока активність (інтенсивні тренування 6-7 разів на тиждень)'), (1.9, 'Дуже висока активність (важкі фізичні навантаження, тренування 2 рази на день)')], default=1.375, help_text='Виберіть рівень вашої фізичної активності'),
        ),
    ]
