# Generated by Django 5.1.6 on 2025-04-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight_goal',
            field=models.FloatField(choices=[(-1.0, 'Схуднути на 1 кг/тиждень'), (-0.5, 'Схуднути на 0.5 кг/тиждень'), (0, 'Підтримувати вагу'), (0.5, 'Набрати 0.5 кг/тиждень'), (1.0, 'Набрати 1 кг/тиждень')], default=0, help_text='Оберіть ціль зміни ваги'),
        ),
    ]
