# Generated by Django 5.1.6 on 2025-04-29 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_weight_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('calories_per_100g', models.FloatField()),
                ('proteins_per_100g', models.FloatField(default=0)),
                ('carbohydrates_per_100g', models.FloatField(default=0)),
                ('fats_per_100g', models.FloatField(default=0)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votes_to_approve', models.ManyToManyField(blank=True, related_name='voted_pending_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
