# Generated by Django 5.1.6 on 2025-04-30 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pendingfooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingfooditem',
            name='status',
        ),
        migrations.AddField(
            model_name='pendingfooditem',
            name='votes_to_reject',
            field=models.ManyToManyField(blank=True, related_name='voted_reject_pending_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingfooditem',
            name='votes_to_approve',
            field=models.ManyToManyField(blank=True, related_name='voted_approve_pending_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
