# Generated by Django 5.1.6 on 2025-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pendingfooditem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('fast_food', 'Фастфуд'), ('fruits', 'Фрукти'), ('vegetables', 'Овочі'), ('meat', "М'ясо"), ('dairy', 'Молочні продукти'), ('grains', 'Крупи'), ('sweets', 'Солодощі'), ('drinks', 'Напої'), ('other', 'Інше')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingfooditem',
            name='category',
            field=models.CharField(choices=[('fast_food', 'Фастфуд'), ('fruits', 'Фрукти'), ('vegetables', 'Овочі'), ('meat', "М'ясо"), ('dairy', 'Молочні продукти'), ('grains', 'Крупи'), ('sweets', 'Солодощі'), ('drinks', 'Напої'), ('other', 'Інше')], default='other', max_length=20),
        ),
    ]
